# Copyright (C) 2019 Peter Schutt
#
# This file is part of fuzzywuzzy-stubs.
#
# fuzzywuzzy-stubs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# fuzzywuzzy-stubs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with fuzzywuzzy-stubs.  If not, see <http://www.gnu.org/licenses/>.

from setuptools import setup
import os

name = "fuzzywuzzy-stubs"
description = "fuzzywuzzy stubs and mypy plugin"

install_instructions = """\
This package generated by mypy stubgen. The 0.0.1 version is purely
just that.

Changelog:
0.0.1: Types for fuzz module.

## Installation

```
pip install fuzzywuzzy-stubs
```

"""


def find_stub_files():
    result = []
    for root, _, files in os.walk(name):
        for file in files:
            if file.endswith(".pyi"):
                if os.path.sep in root:
                    sub_root = root.split(os.path.sep, 1)[-1]
                    file = os.path.join(sub_root, file)
                result.append(file)
    return result


setup(
    name="fuzzywuzzy-stubs",
    version="0.0.1",
    description=description,
    long_description=install_instructions,
    long_description_content_type="text/markdown",
    author="Peter Schutt",
    author_email="peter@topsport.com.au",
    license="GPL",
    url="https://github.com/5uper5hoot/fuzzywuzzy-stubs",
    py_modules=[],
    install_requires=["mypy"],
    packages=["fuzzywuzzy-stubs"],
    package_data={"fuzzywuzzy-stubs": find_stub_files()},
    classifiers=["Development Status :: 3 - Alpha", "Programming Language :: Python :: 3",],
)
