# Copyright (C) 2019 Peter Schutt
#
# This file is part of fuzzywuzzy-stubs.
#
# fuzzywuzzy-stubs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# fuzzywuzzy-stubs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with fuzzywuzzy-stubs.  If not, see <http://www.gnu.org/licenses/>.

# Stubs for fuzzywuzzy.process (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import fuzz
from typing import Any

default_scorer = fuzz.WRatio
default_processor: Any

def extractWithoutOrder(query: Any, choices: Any, processor: Any = ..., scorer: Any = ..., score_cutoff: int = ...): ...
def extract(query: Any, choices: Any, processor: Any = ..., scorer: Any = ..., limit: int = ...): ...
def extractBests(
    query: Any, choices: Any, processor: Any = ..., scorer: Any = ..., score_cutoff: int = ..., limit: int = ...
): ...
def extractOne(query: Any, choices: Any, processor: Any = ..., scorer: Any = ..., score_cutoff: int = ...): ...
def dedupe(contains_dupes: Any, threshold: int = ..., scorer: Any = ...): ...
